config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'

  get "/about", to: 'pages#about'
  resources:posts
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :content, presence: true, length: {maximum: 140} 
  validates :expiration, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum:50 }
  validates :last_name, presence: true, length: { maximum:50 }

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :last_name])
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!
    
    def new
        @post =Post.new
    end

    def index
        @posts = Post.where('expiration >= ?', DateTime.current.midnight)
    end

    def show
        @post = Post.find(params[:id]) #Regresa el post creado
    end

    def create
        @post = current_user.posts.build(post_params)
        if @post.save
            flash[:success] = "Post creado con exito!"
            redirect_to @post #Redirecciona a los post
        else 
            flash.now[:danger] = 'El numero de caracteres o la fecha de expiracion estan incorrectas'
            render 'new'
        end
    end

    def update

    end

    private

    def post_params
        params.require(:post).permit(:content, :expiration)
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<header class = "navbar navbar-top navbar-inverse">
    <div class = "container">
        <%=link_to"FoxPosts", root_path ,id:"logo"%>
        <nav>
        <ul class = "nav navbar-nav navbar-right">
            <li>
                <%=link_to "Home", root_path %>
            </li>
            <li>
            <%=link_to "Acerca de", about_path %>
            </li>
            
            <% unless current_user.blank? %>
                <li>
                    <%= link_to 'Posts', posts_path %>
                </li>    
                <li>
                    <%= link_to 'Crear Nuevo Posts', new_post_path %>
                </li>
                <li>
                    <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
                </li>        
            <% else %>
                <li>
                    <%= link_to 'Register', new_user_registration_path %>
                </li>
                <li>
                    <%= link_to 'Sign In', new_user_session_path %>
                </li>
            <% end %>
        </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>App 2 | <%= (yield(:title) )%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  
  <div>
  <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      
      <%= yield %>
      
    </div>
    
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<% provide(:title,'Acerca de')%>

<div class = "center jumbotron">
    <h1>Acerca de</h1>

    <p>Esta app fue creada tomando <a href="https://twitter.com/" target="_blank">"Twitter"</a> como inspiración, por medio de esta
     se busca que cada cuenta que sea creada tenga la posibilidad de hacer "post" libres de 140 carácteres para que estos sean publicados en una tabla con una fecha de vencimiento de cada publicación</p>

   
</div>

app/views/pages/home.html.erb
<!DOCTYPE html>
<% provide(:title,'Home')%>

<div class = "center jumbotron">
    <% unless current_user.blank? %>
        <h1>
            Bienvenido, <%= "#{current_user.name} #{current_user.last_name}" %>
        </h1>

        <% else %>
            <h1>
                Bienvenido a FoxPosts
            </h1>
            <p> ¡Veo que no estas registrado! <br>
            <%= link_to '¡Registrate Aqui!', new_user_registration_path %> <br>
            Si ya estas registrado <%= link_to '¡Inicia Sesión!', new_user_session_path %>
        </p>
    
    <% end %>
</div>

app/views/posts/index.html.erb
<!DOCTYPE html>
<% provide(:title,'Posts')%>


<div class="formularios" id="tablas">
<h1>Tabla de Posts</h1>

    <% @posts.each do |post| %>
        <div class="post">
            <div class="header">
                <h4><%=  post.user.name %></h4>
            </div>
            <div class="body">
                <p class="card-text"><%= post.content %></p>
                <em class="exp">Expira el <%=  post.expiration %></em>
            </div> 
        </div>

    <% end %>
    
</div>

app/views/posts/new.html.erb
<!DOCTYPE html>
<% provide(:title,'Nuevo Post')%>

<div class="formularios" id="NewPost">
<h1>Nuevo Post</h1>
  <div>
    <%= form_with(model: @post, local: true) do |f| %>

      <div class="form-group">
        <%= f.label "Contenido" %>
        <%= f.text_area :content, :required => true, class: 'form-control' %>
        <em>(Máximos 140 carácteres )</em>
      </div>

      <div class="form-group">
        <%= f.label "Expira el:" %>
        <%= f.date_select :expiration, class: 'form-control' %>
      </div>

      <%= f.submit 'Crear nuevo post', class: 'btn btn-primary form-control' %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<h1>Post</h1>
<div class="row">
    <p><%= @post.content %></p>
    <p><%= @post.expiration %></p>
</div>